### ISSUE TITLE
Switch to cryptography for X509 certificate verification

### ISSUE THREAD

**Issue by jheld** [django-ses/django-ses#182]
Issue #176 is annoying for Mac OS X users, partly because most of us likely use linux as our production target, so any deviation for setup instructions just causes issues and frustration.

I've taken a look at the logic around how M2Crypto is used and it appears that swapping to using `cryptography`'s X509 verification shouldn't take much work.

I'm opening the issue here to see if anyone would be willing to implement before my team does and also if they'd be up for testing it (we'll test but it's always nice having more). The change would also adjust the extra install to use cryptography, effectively removing M2Crypto from the project.

If that's not ideal, we can provide a callable into the library to all projects to use whichever x509 validator they'd like (just give us a function to call to get the certificate info based on the data), but I really hope we don't have to do that and so that won't be part of our code change.

**Comment by pcraciunoiu** [comment]
Hey thanks for filing this!

I'm not actively working on `django-ses`, but I'm happy to maintain it and accept contributions if you or someone else wants to help.

**Comment by jheld** [comment]
Turns out this is not as easy as I expected. Ran into issues with cryptography not providing the full support natively.

**Comment by mlissner** [comment]
@jheld It's been a while since you've looked at this, but switching to using cryptography instead of m2crypto seemed like a good idea to me too and so I wound up here. Do you happen to remember what was complicated about the switch when you last tried? It looks like m2crypto is just used for x509 stuff, and cryptography has a lot of primitives for this: 

https://cryptography.io/en/latest/x509/reference/#loading-certificates

Looks like https://github.com/django-ses/django-ses/issues/205 is a dup of this too, FWTW. There's some demand for the change at least.

If it's not too hard, I could take a stab.

**Comment by jheld** [comment]
Right, so to a degree it is still possible to make the logic swappable for a different crypto backend, but I was having a hard time setting up the other library to get the context executed in the code in place of the existing solution.

It's probably still worth a proof of concept if you have time.

**Comment by mlissner** [comment]
I think we could put some time into this. 

Before we do though, @pcraciunoiu, since some time has passed, can I confirm that a PR would be welcome that removes m2crypto and requires cryptography instead? I think the upgrade path would be smooth and we could just put a release note saying that folks can uninstall m2crypto-dependencies if they want?

**Comment by pcraciunoiu** [comment]
Hi, thanks for helping.

Should we make it an option to choose which, or is the current one deprecated?

I'd be fine to merge the ability, I'm just thinking if anyone using this library has good reason to stick with m2crypto.

**Comment by mlissner** [comment]
Well, I think it's still maintained, but it's definitely *harder* to install and *much* less popular than the `cryptography` package:

`m2crypto`: 

 - 13 commits over last year with latest version 9 months ago
 - Surprisingly, the documentation is almost non-existent: https://m2crypto.readthedocs.io/en/latest/ 
 - **60 dependent packages** (https://libraries.io/pypi/M2Crypto)

Compared to `cryptography`:

 - Latest version two days ago, with detailed change log: https://cryptography.io/en/latest/changelog/
 - Detailed, really good docs: https://cryptography.io/en/latest/
 - **2.6k dependent packages** (https://libraries.io/pypi/cryptography)

Security-wise, I also find it better to use a python-managed dependency than an OS-managed one. A few times now I've stressed that my openssl installation was out of date and I think once I had to urgently upgrade my whole OS to get a new version. Switching to `cryptography` fixes this.

> I'm just thinking if anyone using this library has good reason to stick with `m2crypto`.

My initial thought is that dropping m2crypto completely is fine:

 - Functionality should be the same
 - `cryptography` is a more popular and safer package due to so many more eyes on it and the fact that it doesn't rely on an OS-managed package
 - The installation will be easier, not harder (so most people won't notice the change)
 - The integration points of m2crypto are very few (this isn't deep surgery)

I think it's a rare opportunity to be able to simplify software and we should go for it if we can.

It's probably worth a version bump though, so people actually *read* the release notes.

**Comment by pcraciunoiu** [comment]
Sounds good @mlissner , I'll review the PR once it comes through and we'll likely do a major version bump.

Thank you for taking the time to compare and contrast.

**Comment by pcraciunoiu** [comment]
Sounds good Mike, I'll review the PR once it comes through and we'll likely do a major version bump.

Thank you for taking the time to compare and contrast.
