### ISSUE TITLE
Remove M2Crypto dependency

### ISSUE THREAD

**Issue by aprams** [django-ses/django-ses#205]
M2Crypto currently implies a heavy burden in terms of installing (see e.g. #176).

Using an alternative, more modern library might help to overcome this burden, which can not be easily solved an update in the requirements.txt. 

An example would be [this repository](https://github.com/anfema/django-ses-sns-tracker/tree/e65146fe204088f73c9240bef6cd8e416efb82f1), which used the cryptography package:

https://github.com/anfema/django-ses-sns-tracker/blob/e65146fe204088f73c9240bef6cd8e416efb82f1/ses_sns_tracker/utils.py

I'm by no means an SSL expert, so I'm not sure about the comparability, but it would be a major QoL improvement.

**Comment by pcraciunoiu** [comment]
@aprams thanks for filing and linking to a suggestion! Since I'm not actively using this package, it's tricky for me to do full hands-on testing. But, if you'd like to submit a PR that you've tested, I'm happy to review and try to get it tested and merged.

I like that it was introduced using a setting, so it could be the same here perhaps - giving people the option to stick with M2Crypto or choosing cryptography?

**Comment by joshsny** [comment]
+1 for this issue. Trying to use django-ses[events] in production on Heroku but can't find a way to install m2crypto. Any ideas?

I'd love to submit a PR, unfortunately I do not have the expertise :(

**Comment by joshsny** [comment]
For anyone looking at this who isn't bothered about verifying the events but just wants to receive them, setting `AWS_SES_VERIFY_EVENT_SIGNATURES = False` (**not VERIFY_EVENT_SIGNATURES = False**) did the trick.

**Comment by pcraciunoiu** [comment]
#206 and it was merged. Thanks!
